name: Publish Extension

on:
  release:
    types: [ "published" ]

jobs:
  publish_to_release:
    name: Publish Extension
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Set version variable
      id: vars
      run: |
        echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        echo "output_file="${{ github.event.repository.name }}-${GITHUB_REF#refs/*/}.zip" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@v6

    - name: Update manifest.json version
      run: |
        jq '.version = "${{ steps.vars.outputs.tag }}"' manifest.json > manifest.tmp && mv manifest.tmp manifest.json

    - name: Zip extension
      run: npm run zip

    - name: Rename Zip for Upload
      run: |
        REPO_NAME="${{ github.event.repository.name }}"
        TAG="${{ steps.vars.outputs.tag }}"
        mv "${REPO_NAME}.zip" "${{ steps.vars.outputs.output_file }}"

    - name: Upload Zip
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.release.tag_name }}
        files: ${{ steps.vars.outputs.output_file }}
        append_body: true
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to Chrome Web Store
      uses: mobilefirstllc/cws-publish@2.1.1
      with:
        action: 'publish'
        client_id: ${{ secrets.CHROME_CLIENT_ID }}
        client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
        zip_file: ${{ steps.vars.outputs.output_file }}

    - name: Commit version changes
      run: |
        DEFAULT_BRANCH=${{ github.event.repository.default_branch }}
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add manifest.json
        git diff-index --quiet HEAD || git commit -m "Bump version to ${{ steps.vars.outputs.tag }}"
        git pull --rebase origin ${DEFAULT_BRANCH}
        git push origin HEAD:${DEFAULT_BRANCH}
